#!/usr/bin/python3

import os
import sys
import socket
import threading
import queue
import time
import bson


def send_message(sfd,msg):
    chunk=bson.BSON.encode(msg)
    sfd.send(chunk)
    

def receive_message(sfd):
    header=True
    chunk=b''
    size=0
    remain=0
    while True:
        
        if header:
            hdr=sfd.recv(4)
            size=(hdr[3]<<24) + (hdr[2]<<16) + (hdr[1]<<8) + hdr[0]
            print("incoming packet of {0} bytes".format(size))
            header=False
            chunk=hdr
            remain=size-4
        else:
            
            request=min(remain,4096)
            tmp=sfd.recv(request)
            chunk=chunk+tmp
            remain=remain-request
            
            if remain==0:
                print("package complete")
                header=True
                msg=bson.BSON.decode(chunk)
                return msg

role=sys.argv[1]

broker = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
broker.connect("/tmp/swamp-slave")


t0=0
t1=0

if role=="sender":
    msg={}
    msg["method"]="helo"
    msg["target"]="broker"
    msg["id"]="alfa"
    
    send_message(broker,msg)

    t0=time.time()
    msg={}
    msg["method"]="open_file"
    msg["target"]="beta"
    msg["name"]=sys.argv[2]
    send_message(broker,msg)
    
    msg["method"]="write_file"
    f=open(sys.argv[2],"rb")
    while True:
        chunk=f.read(32767)
        if len(chunk)==0:
            break
        
        msg["data"]=chunk
        send_message(broker,msg)
    f.close()
    
    msg["method"]="close_file"
    msg["data"]=None
    send_message(broker,msg)
    t1=time.time()
    print("Sent in {0} seconds".format(t1-t0))
    
    
if role=="receiver":
    msg={}
    msg["method"]="helo"
    msg["target"]="broker"
    msg["id"]="beta"
    
    send_message(broker,msg)
    
    f=None
    while True:
    
        msg=receive_message(broker)
        
        if msg["method"]=="open_file":
            t0=time.time()
            print("Receiving file...")
            f=open("in-"+msg["name"],"wb")
        if msg["method"]=="close_file":
            t1=time.time()
            print("done")
            f.close()
            print("Received in {0} seconds".format(t1-t0))
        if msg["method"]=="write_file":
            f.write(msg["data"])

    
broker.close()
